// services/notificationService.js - Multi-channel alerts (FR-4.1–FR-4.4)
const nodemailer = require('nodemailer');
const db         = require('../utils/db');

const transporter = nodemailer.createTransport({
  host:   process.env.SMTP_HOST || 'smtp.gmail.com',
  port:   parseInt(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Send email alert
 */
async function sendEmail(to, subject, htmlBody) {
  try {
    const info = await transporter.sendMail({
      from:    process.env.EMAIL_FROM || 'Vahan-Check <noreply@vahancheck.com>',
      to,
      subject,
      html:    htmlBody,
    });
    return { success: true, messageId: info.messageId };
  } catch (err) {
    console.error('Email send error:', err.message);
    return { success: false, error: err.message };
  }
}

/**
 * Simulate WhatsApp alert (logs to DB + console; real integration requires Twilio/WABA)
 */
async function sendWhatsApp(phone, message) {
  console.log(`📱 [WhatsApp Simulation] To: ${phone}\n   Msg: ${message}`);
  return { success: true, simulated: true };
}

/**
 * Build HTML email template for expiry alerts
 */
function buildExpiryEmailHtml(vehicle, docType, daysLeft) {
  const statusLabel = daysLeft <= 0 ? 'EXPIRED' : `Expiring in ${daysLeft} day(s)`;
  const color       = daysLeft <= 0 ? '#ef4444' : '#f59e0b';
  return `
  <div style="font-family: Arial, sans-serif; max-width:600px; margin:auto; border:1px solid #e5e7eb; border-radius:8px; overflow:hidden;">
    <div style="background:#1e3a5f; padding:20px; text-align:center;">
      <h1 style="color:#fff; margin:0; font-size:22px;">🚛 Vahan-Check Alert</h1>
      <p style="color:#93c5fd; margin:4px 0 0;">Fleet Compliance Portal</p>
    </div>
    <div style="padding:24px;">
      <p style="font-size:16px; color:#374151;">Dear Fleet Manager,</p>
      <div style="background:#fef3c7; border-left:4px solid ${color}; padding:16px; border-radius:4px; margin:16px 0;">
        <strong style="color:${color}; font-size:18px;">${statusLabel}</strong>
        <p style="margin:8px 0 0; color:#374151;">
          <strong>${docType}</strong> for vehicle <strong>${vehicle.reg_number}</strong> (${vehicle.make} ${vehicle.model}) 
          ${daysLeft <= 0 ? 'has expired' : `expires on ${vehicle[docType.toLowerCase() + '_expiry']}`}.
        </p>
      </div>
      <table style="width:100%; border-collapse:collapse; margin:16px 0;">
        <tr style="background:#f3f4f6;"><td style="padding:8px; font-weight:bold;">Vehicle</td><td style="padding:8px;">${vehicle.reg_number}</td></tr>
        <tr><td style="padding:8px; font-weight:bold;">Make/Model</td><td style="padding:8px;">${vehicle.make} ${vehicle.model}</td></tr>
        <tr style="background:#f3f4f6;"><td style="padding:8px; font-weight:bold;">Document</td><td style="padding:8px;">${docType}</td></tr>
        <tr><td style="padding:8px; font-weight:bold;">Status</td><td style="padding:8px; color:${color}; font-weight:bold;">${statusLabel}</td></tr>
      </table>
      <p style="color:#6b7280; font-size:14px;">Please take immediate action to avoid penalties. Log in to Vahan-Check portal to view details.</p>
    </div>
    <div style="background:#f9fafb; padding:12px; text-align:center; border-top:1px solid #e5e7eb;">
      <p style="color:#9ca3af; font-size:12px; margin:0;">Generated by Vahan-Check Portal • Data Source: Mock Vahan API / Internal Database</p>
    </div>
  </div>`;
}

/**
 * Log notification to DB
 */
async function logNotification(vehicleId, docType, channel, recipient, message, status, daysBefore) {
  try {
    await db.execute(
      `INSERT INTO notification_logs (vehicle_id, doc_type, channel, recipient, message, status, days_before, sent_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, NOW())`,
      [vehicleId, docType, channel, recipient, message, status, daysBefore]
    );
  } catch (err) {
    console.error('Failed to log notification:', err.message);
  }
}

/**
 * Main dispatch function — sends alert for a specific doc expiry
 */
async function dispatchAlert(vehicle, docType, daysLeft, managerEmail, managerPhone) {
  const results = {};

  // Email
  if (managerEmail) {
    const subject  = `⚠️ ${docType} Alert: ${vehicle.reg_number} — ${daysLeft <= 0 ? 'EXPIRED' : daysLeft + ' days left'}`;
    const html     = buildExpiryEmailHtml(vehicle, docType, daysLeft);
    const emailRes = await sendEmail(managerEmail, subject, html);
    results.email  = emailRes;
    await logNotification(vehicle.id, docType, 'email', managerEmail,
      `${docType} expiry alert for ${vehicle.reg_number}`,
      emailRes.success ? 'sent' : 'failed', daysLeft);
  }

  // WhatsApp (simulated)
  if (managerPhone) {
    const msg   = `🚛 *Vahan-Check Alert*\n${docType} for *${vehicle.reg_number}* (${vehicle.make} ${vehicle.model}) ${daysLeft <= 0 ? 'has EXPIRED' : `expires in ${daysLeft} days`}. Please renew immediately.`;
    const waRes = await sendWhatsApp(managerPhone, msg);
    results.whatsapp = waRes;
    await logNotification(vehicle.id, docType, 'whatsapp', managerPhone,
      msg, waRes.success ? 'sent' : 'failed', daysLeft);
  }

  return results;
}

module.exports = { dispatchAlert, sendEmail, sendWhatsApp, logNotification };