// routes/reports.js - Analytics & CSV export (Section 7)
const router = require('express').Router();
const db     = require('../utils/db');
const { authenticate } = require('../middleware/auth');
const { enrichVehicle, computeKPIs, expiryForecast } = require('../services/complianceService');

// GET /api/reports/dashboard
router.get('/dashboard', authenticate, async (req, res) => {
  try {
    const [vehicles] = await db.execute('SELECT * FROM vehicles');
    const kpis    = computeKPIs(vehicles);
    const forecast = expiryForecast(vehicles);
    const enriched = vehicles.map(enrichVehicle);

    // Document type distribution
    const docDistribution = { Insurance: 0, PUC: 0, Fitness: 0, Permit: 0, Tax: 0 };
    for (const v of enriched) {
      const { docs } = v.compliance;
      for (const [type, status] of Object.entries(docs)) {
        if (status === 'red' || status === 'yellow') {
          if (docDistribution[type] !== undefined) docDistribution[type]++;
        }
      }
    }

    res.json({ success: true, data: { kpis, forecast, docDistribution, total: vehicles.length } });
  } catch (err) {
    res.status(500).json({ success: false, message: 'Failed to load dashboard data' });
  }
});

// GET /api/reports/export-csv
router.get('/export-csv', authenticate, async (req, res) => {
  try {
    const { status, start_date, end_date } = req.query;
    let sql    = `SELECT v.*, u.name AS manager_name FROM vehicles v LEFT JOIN users u ON v.assigned_manager=u.id WHERE 1=1`;
    const args = [];
    if (start_date) { sql += ` AND v.created_at >= ?`; args.push(start_date); }
    if (end_date)   { sql += ` AND v.created_at <= ?`; args.push(end_date); }

    const [vehicles] = await db.execute(sql, args);
    const enriched   = vehicles.map(enrichVehicle);
    const filtered   = status ? enriched.filter(v => v.compliance.overall === status) : enriched;
    const now        = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

    const headers = ['Reg Number','Make','Model','Fuel Type','Vehicle Type','Insurance Expiry','PUC Expiry','Fitness Expiry','RC Expiry','Permit Expiry','Overall Status','Manager'];
    const rows = filtered.map(v => [
      v.reg_number, v.make, v.model, v.fuel_type, v.vehicle_type,
      v.ins_expiry || '', v.puc_expiry || '', v.fit_expiry || '',
      v.rc_expiry || '', v.permit_expiry || '',
      v.compliance.overall, v.manager_name || '',
    ]);

    let csv = headers.join(',') + '\n';
    for (const row of rows) csv += row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',') + '\n';
    csv += `\n"Generated by Vehicle Master on ${now}","Data Source: Mock Vahan API / Internal Database"`;

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="fleet-report-${Date.now()}.csv"`);
    res.send(csv);
  } catch (err) {
    res.status(500).json({ success: false, message: 'Failed to generate report' });
  }
});

// GET /api/reports/notifications
router.get('/notifications', authenticate, async (req, res) => {
  try {
    const [logs] = await db.execute(`
      SELECT n.*, v.reg_number, v.make, v.model
      FROM notification_logs n
      LEFT JOIN vehicles v ON n.vehicle_id=v.id
      ORDER BY n.created_at DESC LIMIT 100
    `);
    res.json({ success: true, data: logs });
  } catch (err) {
    res.status(500).json({ success: false, message: 'Failed to fetch notification logs' });
  }
});

// GET /api/reports/audit
router.get('/audit', authenticate, async (req, res) => {
  try {
    const [logs] = await db.execute(`
      SELECT a.*, u.name AS user_name, v.reg_number
      FROM audit_logs a
      LEFT JOIN users u ON a.user_id=u.id
      LEFT JOIN vehicles v ON a.vehicle_id=v.id
      ORDER BY a.created_at DESC LIMIT 200
    `);
    res.json({ success: true, data: logs });
  } catch (err) {
    res.status(500).json({ success: false, message: 'Failed to fetch audit logs' });
  }
});

module.exports = router;